[phases.setup]
nixPkgs = ["wget", "unzip"]

[phases.build]
cmds = [
  "wget -O pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v0.25.8/pocketbase_0.25.8_linux_amd64.zip && unzip pocketbase.zip && chmod +x pocketbase"
]

[start]
cmd = "./pocketbase serve --http 0.0.0.0:$PORT"

