[phases.setup]
nixPkgs = ["wget", "curl", "jq", "unzip"]

[phases.build]
cmds = [
  "sh -c 'export PB_LATEST=$(curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest | jq -r \".tag_name\") && wget -O pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/$PB_LATEST/pocketbase_linux_amd64.zip && unzip pocketbase.zip && chmod +x pocketbase'"
]

[start]
cmd = "./pocketbase serve --http 0.0.0.0:$PORT"
